/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hardware.nv10;

public class Bills_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Bills_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Bills_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Bills_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NV10ControlJNI.delete_Bills_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setChannel(int value) {
    NV10ControlJNI.Bills_t_Channel_set(swigCPtr, this, value);
  }

  public int getChannel() {
    return NV10ControlJNI.Bills_t_Channel_get(swigCPtr, this);
  }

  public void setBill(int value) {
    NV10ControlJNI.Bills_t_Bill_set(swigCPtr, this, value);
  }

  public int getBill() {
    return NV10ControlJNI.Bills_t_Bill_get(swigCPtr, this);
  }

  public Bills_t() {
    this(NV10ControlJNI.new_Bills_t(), true);
  }

}
