/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hardware.nv10;

public class BillError_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BillError_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BillError_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(BillError_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NV10ControlJNI.delete_BillError_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStatusCode(int value) {
    NV10ControlJNI.BillError_t_StatusCode_set(swigCPtr, this, value);
  }

  public int getStatusCode() {
    return NV10ControlJNI.BillError_t_StatusCode_get(swigCPtr, this);
  }

  public void setBill(int value) {
    NV10ControlJNI.BillError_t_Bill_set(swigCPtr, this, value);
  }

  public int getBill() {
    return NV10ControlJNI.BillError_t_Bill_get(swigCPtr, this);
  }

  public void setMessage(String value) {
    NV10ControlJNI.BillError_t_Message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return NV10ControlJNI.BillError_t_Message_get(swigCPtr, this);
  }

  public BillError_t() {
    this(NV10ControlJNI.new_BillError_t(), true);
  }

}
