/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hardware.nv10;

public class GlobalVariables {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GlobalVariables(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GlobalVariables obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(GlobalVariables obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NV10ControlJNI.delete_GlobalVariables(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNV10Object(NV10Class value) {
    NV10ControlJNI.GlobalVariables_NV10Object_set(swigCPtr, this, NV10Class.getCPtr(value), value);
  }

  public NV10Class getNV10Object() {
    long cPtr = NV10ControlJNI.GlobalVariables_NV10Object_get(swigCPtr, this);
    return (cPtr == 0) ? null : new NV10Class(cPtr, false);
  }

  public void setNV10Pointer(NV10Class value) {
    NV10ControlJNI.GlobalVariables_NV10Pointer_set(swigCPtr, this, NV10Class.getCPtr(value), value);
  }

  public NV10Class getNV10Pointer() {
    long cPtr = NV10ControlJNI.GlobalVariables_NV10Pointer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new NV10Class(cPtr, false);
  }

  public void setSMObject(SMClass value) {
    NV10ControlJNI.GlobalVariables_SMObject_set(swigCPtr, this, SMClass.getCPtr(value), value);
  }

  public SMClass getSMObject() {
    long cPtr = NV10ControlJNI.GlobalVariables_SMObject_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SMClass(cPtr, false);
  }

  public GlobalVariables() {
    this(NV10ControlJNI.new_GlobalVariables(), true);
  }

}
