/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hardware.nv10;

public class NV10ControlClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NV10ControlClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NV10ControlClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(NV10ControlClass obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NV10ControlJNI.delete_NV10ControlClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPortO(int value) {
    NV10ControlJNI.NV10ControlClass_PortO_set(swigCPtr, this, value);
  }

  public int getPortO() {
    return NV10ControlJNI.NV10ControlClass_PortO_get(swigCPtr, this);
  }

  public void setPath(String value) {
    NV10ControlJNI.NV10ControlClass_Path_set(swigCPtr, this, value);
  }

  public String getPath() {
    return NV10ControlJNI.NV10ControlClass_Path_get(swigCPtr, this);
  }

  public void setLogLvl(int value) {
    NV10ControlJNI.NV10ControlClass_LogLvl_set(swigCPtr, this, value);
  }

  public int getLogLvl() {
    return NV10ControlJNI.NV10ControlClass_LogLvl_get(swigCPtr, this);
  }

  public void setMaximumPorts(int value) {
    NV10ControlJNI.NV10ControlClass_MaximumPorts_set(swigCPtr, this, value);
  }

  public int getMaximumPorts() {
    return NV10ControlJNI.NV10ControlClass_MaximumPorts_get(swigCPtr, this);
  }

  public void setGlobals(GlobalVariables value) {
    NV10ControlJNI.NV10ControlClass_Globals_set(swigCPtr, this, GlobalVariables.getCPtr(value), value);
  }

  public GlobalVariables getGlobals() {
    long cPtr = NV10ControlJNI.NV10ControlClass_Globals_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GlobalVariables(cPtr, false);
  }

  public NV10ControlClass() {
    this(NV10ControlJNI.new_NV10ControlClass(), true);
  }

  public void InitLog() {
    NV10ControlJNI.NV10ControlClass_InitLog(swigCPtr, this);
  }

  public Response_t Connect() {
    return new Response_t(NV10ControlJNI.NV10ControlClass_Connect(swigCPtr, this), true);
  }

  public Response_t CheckDevice() {
    return new Response_t(NV10ControlJNI.NV10ControlClass_CheckDevice(swigCPtr, this), true);
  }

  public Response_t StartReader() {
    return new Response_t(NV10ControlJNI.NV10ControlClass_StartReader(swigCPtr, this), true);
  }

  public BillError_t GetBill() {
    return new BillError_t(NV10ControlJNI.NV10ControlClass_GetBill(swigCPtr, this), true);
  }

  public Response_t ModifyChannels(int InhibitMask1) {
    return new Response_t(NV10ControlJNI.NV10ControlClass_ModifyChannels(swigCPtr, this, InhibitMask1), true);
  }

  public Response_t StopReader() {
    return new Response_t(NV10ControlJNI.NV10ControlClass_StopReader(swigCPtr, this), true);
  }

  public Response_t Reject() {
    return new Response_t(NV10ControlJNI.NV10ControlClass_Reject(swigCPtr, this), true);
  }

  public TestStatus_t TestStatus() {
    return new TestStatus_t(NV10ControlJNI.NV10ControlClass_TestStatus(swigCPtr, this), true);
  }

}
