/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hardware.nv10;

public class NV10Class {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NV10Class(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NV10Class obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(NV10Class obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NV10ControlJNI.delete_NV10Class(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSerialPort(int value) {
    NV10ControlJNI.NV10Class_SerialPort_set(swigCPtr, this, value);
  }

  public int getSerialPort() {
    return NV10ControlJNI.NV10Class_SerialPort_get(swigCPtr, this);
  }

  public void setSuccessConnect(boolean value) {
    NV10ControlJNI.NV10Class_SuccessConnect_set(swigCPtr, this, value);
  }

  public boolean getSuccessConnect() {
    return NV10ControlJNI.NV10Class_SuccessConnect_get(swigCPtr, this);
  }

  public void setPortO(int value) {
    NV10ControlJNI.NV10Class_PortO_set(swigCPtr, this, value);
  }

  public int getPortO() {
    return NV10ControlJNI.NV10Class_PortO_get(swigCPtr, this);
  }

  public void setPrevResponseSeq(int value) {
    NV10ControlJNI.NV10Class_PrevResponseSeq_set(swigCPtr, this, value);
  }

  public int getPrevResponseSeq() {
    return NV10ControlJNI.NV10Class_PrevResponseSeq_get(swigCPtr, this);
  }

  public void setLengthData(int value) {
    NV10ControlJNI.NV10Class_LengthData_set(swigCPtr, this, value);
  }

  public int getLengthData() {
    return NV10ControlJNI.NV10Class_LengthData_get(swigCPtr, this);
  }

  public void setErrorOCode(int value) {
    NV10ControlJNI.NV10Class_ErrorOCode_set(swigCPtr, this, value);
  }

  public int getErrorOCode() {
    return NV10ControlJNI.NV10Class_ErrorOCode_get(swigCPtr, this);
  }

  public void setErrorOMsg(String value) {
    NV10ControlJNI.NV10Class_ErrorOMsg_set(swigCPtr, this, value);
  }

  public String getErrorOMsg() {
    return NV10ControlJNI.NV10Class_ErrorOMsg_get(swigCPtr, this);
  }

  public void setErrorOPriority(int value) {
    NV10ControlJNI.NV10Class_ErrorOPriority_set(swigCPtr, this, value);
  }

  public int getErrorOPriority() {
    return NV10ControlJNI.NV10Class_ErrorOPriority_get(swigCPtr, this);
  }

  public void setEventOCode(int value) {
    NV10ControlJNI.NV10Class_EventOCode_set(swigCPtr, this, value);
  }

  public int getEventOCode() {
    return NV10ControlJNI.NV10Class_EventOCode_get(swigCPtr, this);
  }

  public void setEventOMsg(String value) {
    NV10ControlJNI.NV10Class_EventOMsg_set(swigCPtr, this, value);
  }

  public String getEventOMsg() {
    return NV10ControlJNI.NV10Class_EventOMsg_get(swigCPtr, this);
  }

  public void setEventOPriority(int value) {
    NV10ControlJNI.NV10Class_EventOPriority_set(swigCPtr, this, value);
  }

  public int getEventOPriority() {
    return NV10ControlJNI.NV10Class_EventOPriority_get(swigCPtr, this);
  }

  public void setLROCode(int value) {
    NV10ControlJNI.NV10Class_LROCode_set(swigCPtr, this, value);
  }

  public int getLROCode() {
    return NV10ControlJNI.NV10Class_LROCode_get(swigCPtr, this);
  }

  public void setLROMsg(String value) {
    NV10ControlJNI.NV10Class_LROMsg_set(swigCPtr, this, value);
  }

  public String getLROMsg() {
    return NV10ControlJNI.NV10Class_LROMsg_get(swigCPtr, this);
  }

  public void setLROPriority(int value) {
    NV10ControlJNI.NV10Class_LROPriority_set(swigCPtr, this, value);
  }

  public int getLROPriority() {
    return NV10ControlJNI.NV10Class_LROPriority_get(swigCPtr, this);
  }

  public void setAdEventOCode(int value) {
    NV10ControlJNI.NV10Class_AdEventOCode_set(swigCPtr, this, value);
  }

  public int getAdEventOCode() {
    return NV10ControlJNI.NV10Class_AdEventOCode_get(swigCPtr, this);
  }

  public void setAdEventOMsg(String value) {
    NV10ControlJNI.NV10Class_AdEventOMsg_set(swigCPtr, this, value);
  }

  public String getAdEventOMsg() {
    return NV10ControlJNI.NV10Class_AdEventOMsg_get(swigCPtr, this);
  }

  public void setAdEventOPriority(int value) {
    NV10ControlJNI.NV10Class_AdEventOPriority_set(swigCPtr, this, value);
  }

  public int getAdEventOPriority() {
    return NV10ControlJNI.NV10Class_AdEventOPriority_get(swigCPtr, this);
  }

  public void setBill(int value) {
    NV10ControlJNI.NV10Class_Bill_set(swigCPtr, this, value);
  }

  public int getBill() {
    return NV10ControlJNI.NV10Class_Bill_get(swigCPtr, this);
  }

  public void setChannel(int value) {
    NV10ControlJNI.NV10Class_Channel_set(swigCPtr, this, value);
  }

  public int getChannel() {
    return NV10ControlJNI.NV10Class_Channel_get(swigCPtr, this);
  }

  public void setLoggerLevel(int value) {
    NV10ControlJNI.NV10Class_LoggerLevel_set(swigCPtr, this, value);
  }

  public int getLoggerLevel() {
    return NV10ControlJNI.NV10Class_LoggerLevel_get(swigCPtr, this);
  }

  public void setLogFilePath(String value) {
    NV10ControlJNI.NV10Class_LogFilePath_set(swigCPtr, this, value);
  }

  public String getLogFilePath() {
    return NV10ControlJNI.NV10Class_LogFilePath_get(swigCPtr, this);
  }

  public void setMaxPorts(int value) {
    NV10ControlJNI.NV10Class_MaxPorts_set(swigCPtr, this, value);
  }

  public int getMaxPorts() {
    return NV10ControlJNI.NV10Class_MaxPorts_get(swigCPtr, this);
  }

  public NV10Class() {
    this(NV10ControlJNI.new_NV10Class(), true);
  }

  public SpdlogLevels_t SearchSpdlogLevel(int Code) {
    return new SpdlogLevels_t(NV10ControlJNI.NV10Class_SearchSpdlogLevel(swigCPtr, this, Code), true);
  }

  public void SetSpdlogLevel() {
    NV10ControlJNI.NV10Class_SetSpdlogLevel(swigCPtr, this);
  }

  public ErrorCodes_t SearchErrorCodeExComm(int Code) {
    return new ErrorCodes_t(NV10ControlJNI.NV10Class_SearchErrorCodeExComm(swigCPtr, this, Code), true);
  }

  public Bills_t SearchBill(int Channel) {
    return new Bills_t(NV10ControlJNI.NV10Class_SearchBill(swigCPtr, this, Channel), true);
  }

  public ErrorCodes_t SearchErrorCodes(int Code) {
    return new ErrorCodes_t(NV10ControlJNI.NV10Class_SearchErrorCodes(swigCPtr, this, Code), true);
  }

  public ErrorCodes_t SearchEventCodes(int Code) {
    return new ErrorCodes_t(NV10ControlJNI.NV10Class_SearchEventCodes(swigCPtr, this, Code), true);
  }

  public ErrorCodes_t SearchLastReject(int Code) {
    return new ErrorCodes_t(NV10ControlJNI.NV10Class_SearchLastReject(swigCPtr, this, Code), true);
  }

  public int StIdle() {
    return NV10ControlJNI.NV10Class_StIdle(swigCPtr, this);
  }

  public int StConnect() {
    return NV10ControlJNI.NV10Class_StConnect(swigCPtr, this);
  }

  public int StDisable() {
    return NV10ControlJNI.NV10Class_StDisable(swigCPtr, this);
  }

  public int StEnable() {
    return NV10ControlJNI.NV10Class_StEnable(swigCPtr, this);
  }

  public int StPolling() {
    return NV10ControlJNI.NV10Class_StPolling(swigCPtr, this);
  }

  public int StCheck() {
    return NV10ControlJNI.NV10Class_StCheck(swigCPtr, this);
  }

  public int StError() {
    return NV10ControlJNI.NV10Class_StError(swigCPtr, this);
  }

  public void InitLogger(String Path) {
    NV10ControlJNI.NV10Class_InitLogger(swigCPtr, this, Path);
  }

  public int ConnectSerial(int Port) {
    return NV10ControlJNI.NV10Class_ConnectSerial(swigCPtr, this, Port);
  }

  public int ScanPorts() {
    return NV10ControlJNI.NV10Class_ScanPorts(swigCPtr, this);
  }

  public int GetSeq() {
    return NV10ControlJNI.NV10Class_GetSeq(swigCPtr, this);
  }

  public SWIGTYPE_p_std__vectorT_unsigned_char_t CalcCRC(SWIGTYPE_p_std__vectorT_unsigned_char_t Comm) {
    return new SWIGTYPE_p_std__vectorT_unsigned_char_t(NV10ControlJNI.NV10Class_CalcCRC(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Comm)), true);
  }

  public SWIGTYPE_p_std__vectorT_unsigned_char_t BuildCmd(SWIGTYPE_p_std__vectorT_unsigned_char_t Comm) {
    return new SWIGTYPE_p_std__vectorT_unsigned_char_t(NV10ControlJNI.NV10Class_BuildCmd(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Comm)), true);
  }

  public int SendingCommand(SWIGTYPE_p_std__vectorT_unsigned_char_t Comm) {
    return NV10ControlJNI.NV10Class_SendingCommand(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Comm));
  }

  public int ExecuteCommand(SWIGTYPE_p_std__vectorT_unsigned_char_t Comm) {
    return NV10ControlJNI.NV10Class_ExecuteCommand(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Comm));
  }

  public int HandleResponse(SWIGTYPE_p_std__vectorT_unsigned_char_t Response) {
    return NV10ControlJNI.NV10Class_HandleResponse(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Response));
  }

  public int HandleCode(SWIGTYPE_p_std__vectorT_unsigned_char_t Response) {
    return NV10ControlJNI.NV10Class_HandleCode(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Response));
  }

  public int HandleEvent(SWIGTYPE_p_std__vectorT_unsigned_char_t Response) {
    return NV10ControlJNI.NV10Class_HandleEvent(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Response));
  }

  public int HandleLRC(SWIGTYPE_p_std__vectorT_unsigned_char_t Response) {
    return NV10ControlJNI.NV10Class_HandleLRC(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Response));
  }

  public int HandleChannel(SWIGTYPE_p_std__vectorT_unsigned_char_t Response) {
    return NV10ControlJNI.NV10Class_HandleChannel(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Response));
  }

  public int DisplayOn() {
    return NV10ControlJNI.NV10Class_DisplayOn(swigCPtr, this);
  }

  public int DisplayOff() {
    return NV10ControlJNI.NV10Class_DisplayOff(swigCPtr, this);
  }

  public int SetChannels() {
    return NV10ControlJNI.NV10Class_SetChannels(swigCPtr, this);
  }

  public int Enable() {
    return NV10ControlJNI.NV10Class_Enable(swigCPtr, this);
  }

  public int Disable() {
    return NV10ControlJNI.NV10Class_Disable(swigCPtr, this);
  }

  public int Poll() {
    return NV10ControlJNI.NV10Class_Poll(swigCPtr, this);
  }

  public int LastReject() {
    return NV10ControlJNI.NV10Class_LastReject(swigCPtr, this);
  }

  public int Sync() {
    return NV10ControlJNI.NV10Class_Sync(swigCPtr, this);
  }

  public int Hold() {
    return NV10ControlJNI.NV10Class_Hold(swigCPtr, this);
  }

  public int Reject() {
    return NV10ControlJNI.NV10Class_Reject(swigCPtr, this);
  }

}
